version: "3.9"

services:
  api:
    image: alex1995174/api:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 8000:8000
    volumes:
      - ./:/todolist
    platform: linux/amd64
    links:
      - pg
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 588114bfiF
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  front:
    image: 14a79381ab41b94844bc9705c415969bdaaab25b574c4fe29d35df68ccca611f
    links:
      - api
    ports:
      - 80:80