version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: alex1995174/api
    ports:
      - 8000:8000
    volumes:
      - ./:/todolist
    depends_on:
      pg:
        condition: service_healthy
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 588114bfiF
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  front:
    image: 14a79381ab41b94844bc9705c415969bdaaab25b574c4fe29d35df68ccca611f
    depends_on:
      - api
    ports:
      - 80:80





