version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    environment:
      HOST_DB: pg
    depends_on:
      pg:
        condition: service_healthy
#    ports:
#      - 8000:8000
    volumes:
      - ./:/opt/todolist
  pg:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 5
  front:
    image: sermalenk/skypro-front:lesson-37
    links:
      - api
    ports:
      - 80:80