version: "3.9"

services:
  api:
    image: ${DOCKER_USERNAME}/api:latest
    restart: always
    env_file:
      - ./.env
    environment:
      HOST_DB: pg
    depends_on:
      pg:
        condition: service_healthy
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  front:
    image: 14a79381ab41b94844bc9705c415969bdaaab25b574c4fe29d35df68ccca611f
    links:
      - api
    ports:
      - 80:80